//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challenge
    {
        public System.Guid ChallengeId { get; set; }
        public System.Guid SendingUserId { get; set; }
        public System.Guid ReceivingUserId { get; set; }
        public System.Guid GameId { get; set; }
        public string Message { get; set; }
        public bool Seen { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
    }
}
