//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAchievements
    {
        public System.Guid UserAchievementId { get; set; }
        public System.Guid AchievementId { get; set; }
        public System.Guid UserInfoId { get; set; }
        public bool Achieved { get; set; }
    
        public virtual Achievements Achievements { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
