//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace FindIt.Models
{
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class UserAchievements
    {
        [DataMember]
        public System.Guid UserAchievementId { get; set; }
        [DataMember]
        public System.Guid AchievementId { get; set; }
        [DataMember]
        public System.Guid UserInfoId { get; set; }
        [DataMember]
        public bool Achieved { get; set; }
    
        public virtual Achievements Achievements { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
